### ISSUE TITLE
Question regarding to the implicit resolution in Lesson 42

### ISSUE THREAD

**Issue by wshito** [DanielaSfregola/get-programming-with-scala#101]
Hi, I have a question about implicit resolution explained in Lesson 42.

Your "Try This" answer imports the typeclass implementation as [import Money.numeric._](https://github.com/DanielaSfregola/get-programming-with-scala/blob/60463c90627170082978e0d7b4a6644ebf80903a/unit7/lesson42/src/main/scala/trythis/TryThis-42.1.sc#L82).

According to the page 386, we should be able to import as `import Money.given` but it gets compile error.  According to figure 42.3 on page 387, it should even get resolved without importing since `given` declaration resides in the companion object.  Why do we need to import as `import Money.numeric._` in this case?

**Comment by DanielaSfregola** [comment]
Hi @wshito,
the hint you are looking for is in this comment:

```
  // The import enables
  // a more compact syntax you can use with numeric types
```

`import Money.numeric._` is only needed to use the nice `+` and `-` syntax, not to resolve the implicit Numeric[Money] correctly.

Note that the following code (objectively more ugly) will also work:
```
  // let's not import Money.numeric._

  implicitly[Numeric[Money]].plus(Money(1, GBP), Money(10, GBP))
  implicitly[Numeric[Money]].minus(Money(100, USD), Money(42, EUR))
```

`implicitly[T]` is a function that finds and returns an implicit instance for that type T.
Have a look at the implementation of `Numeric` where they have an implicit conversion for the + and - functions: https://github.com/scala/scala/blob/2.13.x/src/library/scala/math/Numeric.scala#L247-L260.

I hope this helps!

Cheers,
D.

**Comment by wshito** [comment]
Thank you for your reply @DanielaSfregola 

I understand that the given instance is within the scope without importing since `implicitly[T]` can summon it.  But I still don't understand what `import Money.numeric._` is actually importing if it is not for the given instance.

I supposed that it imports the overriding methods.  So I experimented the code below.  Now, `Money` is `Numeric[Money]` by implementing the trait, however it does not work as expected.

When I read Odersky's book (5th ed.), the `given` declaration is used with the keyword `using` .  But here, the given instance is standalone.  I don't know how it works in your case.

```scala
import java.util.{Currency, Locale}

case class Money(
    amount: Double,
    currency: Currency = Currency.getInstance(Locale.JAPAN)
) extends Numeric[Money]:
  def fromInt(x: Int) = Money(x.toDouble)
  def minus(x: Money, y: Money): Money =
    Money(x.amount - y.amount, x.currency)
  def negate(x: Money): Money = x.copy(amount = -x.amount)
  def parseString(str: String): Option[Money] =
    try Some(Money(str.toDouble))
    catch case e => None
  def plus(x: Money, y: Money): Money =
    Money(x.amount + y.amount, x.currency)
  def times(x: Money, y: Money): Money =
    Money(x.amount * y.amount, x.currency)
  def toDouble(x: Money): Double = x.amount
  def toFloat(x: Money): Float = x.amount.toFloat
  def toInt(x: Money): Int = x.amount.toInt
  def toLong(x: Money): Long = x.amount.toLong
  def compare(x: Money, y: Money): Int = x.amount.compare(y.amount)

@main def main: Unit =
  import scala.math.Numeric.mkNumericOps
  println(Money(100) + Money(10))
```

**Comment by wshito** [comment]
I finally understand your explanation fully.  In the above case, I had to instantiate Money to import `mkNumericOps`.  Thank you very much for your help!
