### ISSUE TITLE
welcome method not interpolating string correctly

### ISSUE THREAD

**Issue by kevin-orr** [DanielaSfregola/get-programming-with-scala#80]
Hiya Daniela,

In listing §7.5 the welcome method for `Robot` is missing the interpolation operator `s".."`, so it should look like:

```scala
def welcome(n: String) = s"Welcome $n! My name is $name"
```
rather than:

https://github.com/DanielaSfregola/get-programming-with-scala/blob/6a567588f6d72c425e13457de0d7acc500685cea/unit1/lesson7/src/main/scala/listings/Listing-7.5.sc#L2

**Comment by DanielaSfregola** [comment]
Thanks @kevin-orr!  LGTM
And Sorry it took so long to notice this PR - notifications on new prs were off 🤦

**Comment by DanielaSfregola** [comment]
Closing as I have fixed it in https://github.com/DanielaSfregola/get-programming-with-scala/pull/58/files
