### ISSUE TITLE
"dead code following this construct" error found in PostgreSQLContainer

### ISSUE THREAD

**Issue by timshen24** [DanielaSfregola/get-programming-with-scala#96]
My dependencies are exactly the same as those in the book 
```
    "org.testcontainers" % "postgresql" % "1.15.3",
    "org.postgresql" % "postgresql" % "42.2.22",
```

However, I suffered "dead code following this construct" error in the line of 
`val psql: PostgreSQLContainer[_] =
      new PostgreSQLContainer(imageVersion).withInitScript(initScript)`

What can I do to fix this plz?

**Comment by DanielaSfregola** [comment]
Hi @timshen24,
have you tried running the code of this repo? Does the issue still persist if you do that?

Cheers,
Daniela

**Comment by timshen24** [comment]
Mam... after adding `scalacOptions -= "-Xfatal-warnings"` to the `build.sbt`, the `dead code following this construct` error now turns into a warning...

1. But is there a thorough solution to completely removing any errors or warnings eventually? Hope to get your instructions.

And when I run the code by 
`import org.example.registrations._
val psqlServer = new PostgreSQL("init.sql")` (on page 427)
It ended up with ```Attempted to read Testcontainers configuration file at file:/Users/tim.shen/.testcontainers.properties but the file was not found. Exception message: FileNotFoundException: /Users/tim.shen/.testcontainers.properties (No such file or directory)```
and ```docker-machine executable was not found on PATH ([/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/bin/, /Users/tim.shen/Software/apache-maven-3.6.3/bin, /usr/local/sbin, /usr/local/bin, ~/bin, /usr/local/bin, /usr/bin, /bin, /usr/sbin, /sbin, /usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Vers......```
and ```org.testcontainers.dockerclient.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration.```

I have definitely installed docker on my machine: 
```❯ docker --version
Docker version 20.10.7, build f0df350```

2. How can I deal with these errors? As the book seems not mentioning how to fix them... Thank you ahead

**Comment by DanielaSfregola** [comment]
Hi @timshen24,
The compiler error indicates there is an error in your code -- please compare the code you have with its solution in this repo. This StackOverflow question may also be useful to understand why this is happening: https://stackoverflow.com/questions/22046153/why-do-i-get-dead-code-following-this-construct-with-the-following-code

`after adding scalacOptions -= "-Xfatal-warnings" to the build.sbt, the dead code following this construct error now turns into a warning...` ...do you mean removing the flag? The `fatal-warnings` flag converts compiler warnings into errors - more info on this https://docs.scala-lang.org/overviews/compiler-options/index.html. Messing with the compiler flags to downgrade your errors into warnings doesn't solve your problem, but rather only hides it.

The message `Could not find a valid Docker environment. Please check configuration.` also suggest that your docker environment may not be set up correctly. I would advise making sure your Docker environment is set up correctly by running the sample application from the Docker documentation: https://docs.docker.com/get-started/02_our_app/

I strongly recommend you to check out and run the solution contained in this repo as part of your investigation: if the solution runs, then you only have a code-related problem. If the solution doesn't run, you could also have setup issues related to Docker.

Cheers,
Daniela

**Comment by timshen24** [comment]
Thank you for giving me tips and advices. I've found your repository is right, but mine still has the problem, which I don't know why, because in my build.sbt file, the versions are exactly the same as yours...

**Comment by DanielaSfregola** [comment]
Hi @timshen24,
having the same build.sbt file is not enough: your Scala implementation must also be correct.

You should be able to spot the error by comparing what you have with the solution.

Cheers,
Daniela

**Comment by DanielaSfregola** [comment]
I imagine this is solved now -- if needed, please reopen the ticket
