### ISSUE TITLE
The field should be a method

### ISSUE THREAD

**Issue by wshito** [DanielaSfregola/get-programming-with-scala#98]
https://github.com/DanielaSfregola/get-programming-with-scala/blob/ed86815efd9ee59eb35c59eb3116029de53e12ca/unit2/lesson10/src/main/scala/listings/Listing-10.4.sc#L11

In Listing 10.4, the field `var cost` is initialized in the primary constructor and gets never updated since then.  It should be `def cost`.

**Comment by DanielaSfregola** [comment]
Hi @wshito, 
thanks for raising this, you are right!

```
val myParty = new Party
myParty.cost
myParty.register(500)
myParty.cost
```
The current (buggy) code results in the following:

```
val myParty: Party = Party@3b3056a6
val res0: Double = 50.0
val res2: Double = 50.0
```

If I can `cost` to be a `def` rather than a `var`, I get the intended behavior:
```
val myParty: Party = Party@35e3f3b8
val res3: Double = 50.0
val res5: Double = 6170.0
```
I'll raise a PR to fix the code here and add it to the book's errata.

Cheers,
Daniela

**Comment by emaphis** [comment]
Update the Quick Check 10.3  answer too.

**Comment by DanielaSfregola** [comment]
Hi @emaphis,
thanks for pointing that out! I have fixed that too.

Cheers,
D.
